### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by vvuonghn** [Zeyu-Zhu/PGCU#2]
Hi @Zeyu-Zhu 

Thank you for your paper.  I am very excited about your method
Could you share the dataset you use in your research

Thank you

**Comment by Zeyu-Zhu** [comment]
You can find the datasets we used in: https://github.com/manman1995/pansharpening. It was private datasets before, but it's uploaded open source by Dr. Man Zhou. Hope everything goes well.
