### ISSUE TITLE
test or inference

### ISSUE THREAD

**Issue by zahrabsh74** [Zeyu-Zhu/PGCU#3]
dear @Zeyu-Zhu  , thanks for your nice work.
I wanted to run your code on my own dataset but I couldn't find any test.py or inference code. Is it possible to please release the test or inference code on your model?

**Comment by Zeyu-Zhu** [comment]
Thank you. To test the model, you can just load the parameter(e.g. torch.load()) of the model and use forward function(e.g. model.forward()).
