### ISSUE TITLE
How to use this model to inference on new worldview3 imagery?

### ISSUE THREAD

**Issue by kaushikCanada** [Zeyu-Zhu/PGCU#4]
Hello,

FIrst of all, congratulations for htis wonderful paper! I am a new graduate student an INRS, Quevec. I have some worldview 3 imagery that I want to pansharpen using this model. Can you please show me how to prepare my data?

**Comment by Zeyu-Zhu** [comment]
Hi, @kaushikCanada.
Thank you for your attention to our paper.
 If you would like to test the model using your own dataset, first you need to train the model on your training dataset and then test it on the testing dataset. Or you can try to load the params in  'result/PanNet/WV3exp0/PanNet_pgcu.pkl' which is PGCU with PanNet and inference your own data. 
It's worth noting that our implementation of PGCU is used to upsample LRMS to the scale of PAN while PAN is four times the size of LRMS.  If you want to change it, you may add MaxPooling or Conv2d with stride=2 to make the information matrix extracted from LRMS and PAN to be in the same size and train your own model.

**Comment by Zeyu-Zhu** [comment]
Btw, if you want to try to load the params in 'result/PanNet/WV3exp0/PanNet_pgcu.pkl' which is PGCU with PanNet and inference your own data, please follow the preprocessing method in our paper.
